
name: github-script

on:
  # workflow_dispatch:
  push:

env:
  USER_NAME: "mask"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      # - name: Tag commit
      #   uses: tvdias/github-tagger@v0.0.2
      #   with:
      #     repo-token: "${{ secrets.GH_TOKEN }}"
      #     tag: "0.02"
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/0.0.6',
              sha: context.sha
            })
