
name: github-script

on:
  # workflow_dispatch:
  push:

env:
  USER_NAME: "mask"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      # - name: Tag commit
      #   uses: tvdias/github-tagger@v0.0.2
      #   with:
      #     repo-token: "${{ secrets.GH_TOKEN }}"
      #     tag: "0.02"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          custom_tag: "0.0.5"
