
name: github-script

on:
  workflow_dispatch:
  push:

env:
  USER_NAME: "mask"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
        # id: extract_branch
  
      # - name: Tag commit
      #   uses: tvdias/github-tagger@v0.0.2
      #   with:
      #     repo-token: "${{ secrets.GH_TOKEN }}"
      #     tag: "0.02"
      
      - name: Set Dist Version
        run: |
          # build_number="${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
          # echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV
          time_stamp="$(date +'%Y.%m.%d')"
          echo "NOW=$time_stamp" >> $GITHUB_ENV
          
      # - name: Set TIME
      #   run: |
      #     echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      #     echo "${{env.NOW}}"
    
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.run_number }}-${{env.NOW}}-${{env.branch}}',
              sha: context.sha
            })
      # - name: Run latest-tag
      #   uses: EndBug/latest-tag@latest
      #   with:
      #     tag-name: 0.0.7
