name: github-script
  
on:  
  workflow_dispatch:  
  push:
    branches:
      - '**'
    # tags: 
    #   - '!v*'

env:  
  USER_NAME: "mask" 
  
jobs:  
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4

      # - name: Extract branch name
      #   run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      #   # id: extract_branch
  
      # - name: Tag commit
      #   uses: tvdias/github-tagger@v0.0.2
      #   with:
      #     repo-token: "${{ secrets.GH_TOKEN }}"
      #     tag: "0.02"
      
      # - name: Set Dist Version
      #   run: |
      #     # build_number="${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
      #     # echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV
      #     time_stamp="$(date +'%Y.%m.%d')"
      #     echo "NOW=$time_stamp" >> $GITHUB_ENV
      #     echo "${{ github.ref_name }}"
          
      # - name: Set outputs
      #   id: vars
      #   run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
      # - name: Set TIME
      #   run: |
      #     echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      #     echo "${{env.NOW}}"
    
      # - name: Create tag
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/${{ github.run_number }}-${{env.NOW}}-${{ env.sha_short }}',
      #         sha: context.sha
      #       })
      # - name: Run latest-tag
      #   uses: EndBug/latest-tag@latest
      #   with:
      #     tag-name: 0.0.7

      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      #   env:
      #     # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # if you don't want to set write permissions use a PAT token
      #     WITH_V: false
      
      # - name: Bump version and push tag
      #   uses: hennejg/github-tag-action@v4.1.jh1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
    
      # - uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      
      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}

              
      # - name: Autotag      
      #   uses: phish108/autotag-action@v1.1.64

      # - name: Auto tag         
      #   uses: Klemensas/action-autotag@1.2.3
      #   with:
      #     GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"

      # - name: Conventional Changelog Action
      #   uses: TriPSs/conventional-changelog-action@v5.2.1
      #   with:
      #     github-token: ${{ secrets.GH_TOKEN }}
      
      # - name: Create/Update tag    
      #   uses: rickstaa/action-create-tag@v1.7.2
      #   with:
      #     tag: "${{ github.run_number }}" 
      
      # - name: Updated related tags
      #   uses: haya14busa/action-update-semver@v1.2.1
      #   with:
      #     tag: "${{ github.run_number }}"
      
    
      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     dry_run: true
         
      # - name: Git Semantic Version 
      #   id: tag_version
      #   uses: PaulHatch/semantic-version@v5.4.0
      #   with:
      #     # tag_prefix: "v"
      #     major_pattern: "MAJOR"
      #     minor_pattern: "MINOR"
      
      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # if you don't want to set write permissions use a PAT token
      #     WITH_V: false

      # - name: Create Tag
      #   id: create_tag
      #   uses: jaywcjlove/create-tag-action@main
      
      # - name: Bump version and push tag
      #   uses: hennejg/github-tag-action@v4.3.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      
      # - name: Bump version and push tag
      #   if: github.event_name == 'workflow_dispatch'
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
       
      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: miguelfito/github-bump-and-tag-action@v1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}

      # - name: Create a GitHub release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.tag_version.outputs.new_tag }}
      #     release_name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ steps.tag_version.outputs.changelog }}
      
      # - uses: jveldboom/action-conventional-versioning@v1
      #   id: version

      # - name: Create GitHub Release
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: |
      #     gh release create "${{ steps.version.outputs.version-with-prefix }}" \
      #       --generate-notes \
      #       --target "${{ github.sha }}"

      # - name: Update Major Tag
      #   # env:
      #   #   MAJOR: ${{ steps.version.outputs.major }} 
      #   run: |
      #     git tag -d 0.0.1 || true
      #     git push origin :refs/tags/0.0.1
      #     git tag 0.0.1 
      #     git push origin 0.0.1

      # - name: Update major/minor semver  
      #   uses: haya14busa/action-update-semver@v1.2.1


      # - name: Create tag
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/${{ steps.tag_version.outputs.version }}',
      #         sha: context.sha
      #       })
      
      # - name: Create Release
      #   id: create_release
      #   uses: xaprier/actions-semver@latest
      #   with:
      #     draft: false
      #     prerelease: false
      #     include-letter-v: true
      #     token: ${{ secrets.GH_TOKEN }}
      

      # - name: Bump version and push tag
      #   uses: hennejg/github-tag-action@v4.3.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}


  Tags:
    runs-on: ubuntu-latest
    # if: github.event_name == 'workflow_dispatch'
    concurrency: ci-${{ github.ref }}
    permissions: write-all
    # needs: build
    steps:  
      - name: checkout repo
        uses: actions/checkout@v4
      # - name: Minor version for each merge
      #   id: taggerDryRun
      #   uses: anothrNick/github-tag-action@1.67.0
      #   env:
      #     # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     WITH_V: true
      #     DEFAULT_BUMP: patch
      #     # DRY_RUN: true
  
      # - name: echo new tag
      #   run: |
      #     echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"
      # - name: echo tag
      #   run: |
      #     echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
      # - name: echo part
      #   run: |
      #     echo "The version increment was: ${{ steps.taggerDryRun.outputs.part }}"

      # - name: Increment version
      #   id: increment-version
      #   uses: RichardInnocent/semantic-versioning-git@v0.0.2

      # # Everything below here shows how you might use the results of the action...

      # - name: Print if version changed
      #   # if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
      #   run: echo "The new version is now $new_version"
      #   env:
      #     new_version: ${{ steps.increment-version.outputs.new-version }}
          
      # - name: Create tag
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/${{ steps.increment-version.outputs.new-version }}',
      #         sha: context.sha
      #       })
      
      - uses: paulhatch/semantic-version@v5.3.0
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
          # A string which indicates the flags used by the `major_pattern` regular expression. Supported flags: idgs
          major_regexp_flags: ""
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
          # A string which indicates the flags used by the `minor_pattern` regular expression. Supported flags: idgs
          minor_regexp_flags: ""
          # A string to determine the format of the version output
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          change_path: "src/my-service"
          # Named version, will be used as suffix for name version tag
          namespace: my-service
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: false
          # If bump_each_commit is also set to true, setting this value will cause the version to increment only if the pattern specified is matched.
          bump_each_commit_patch_pattern: ""
          # If true, the body of commits will also be searched for major/minor patterns to determine the version type.
          search_commit_body: false
          # The output method used to generate list of users, 'csv' or 'json'.
          user_format_type: "csv"
          # Prevents pre-v1.0.0 version from automatically incrementing the major version.
          # If enabled, when the major version is 0, major releases will be treated as minor and minor as patch. Note that the version_type output is unchanged.
          enable_prerelease_mode: true
          # If enabled, diagnostic information will be added to the action output.
          debug: false
          # If true, the branch will be used to select the maximum version.
          version_from_branch: false
