name: github-script

on:
  workflow_dispatch:
  push:

env:
  USER_NAME: "mask"

jobs: 
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Extract branch name
      #   run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      #   # id: extract_branch
  
      # - name: Tag commit
      #   uses: tvdias/github-tagger@v0.0.2
      #   with:
      #     repo-token: "${{ secrets.GH_TOKEN }}"
      #     tag: "0.02"
      
      # - name: Set Dist Version
      #   run: |
      #     # build_number="${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
      #     # echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV
      #     time_stamp="$(date +'%Y.%m.%d')"
      #     echo "NOW=$time_stamp" >> $GITHUB_ENV
      #     echo "${{ github.ref_name }}"
          
      # - name: Set outputs
      #   id: vars
      #   run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
      # - name: Set TIME
      #   run: |
      #     echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      #     echo "${{env.NOW}}"
    
      # - name: Create tag
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/${{ github.run_number }}-${{env.NOW}}-${{ env.sha_short }}',
      #         sha: context.sha
      #       })
      # - name: Run latest-tag
      #   uses: EndBug/latest-tag@latest
      #   with:
      #     tag-name: 0.0.7

      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      #   env:
      #     # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # if you don't want to set write permissions use a PAT token
      #     WITH_V: false
      
      # - name: Bump version and push tag
      #   uses: hennejg/github-tag-action@v4.1.jh1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
    
      # - uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      
      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}

              
      # - name: Autotag      
      #   uses: phish108/autotag-action@v1.1.64

      # - name: Auto tag         
      #   uses: Klemensas/action-autotag@1.2.3
      #   with:
      #     GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"

      # - name: Conventional Changelog Action
      #   uses: TriPSs/conventional-changelog-action@v5.2.1
      #   with:
      #     github-token: ${{ secrets.GH_TOKEN }}
      
      - name: Create/Update tag    
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: "${{ github.run_number }}"
 
