
name: github-script

on:
  # workflow_dispatch:
  push:

env:
  USER_NAME: "mask"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      # - uses: actions/github-script@v7
      #   id: set-result
      #   with:
      #     script: return "Hello!"
      #     result-encoding: string
      # - name: Get result
      #   run: echo "${{steps.set-result.outputs.result}}"
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GH_TOKEN }}"
          tag: "0.02"
