name: github-script
  
on:  
  workflow_dispatch:   
  push:
    branches: 
      - '**' 
      
    # tags: 
    #   - '!v*'  

# env:   
#   USER_NAME: "mask" 
  
jobs:  
  # build: 
  #   runs-on: windows-latest
  #   permissions: write-all 
  #   steps:
  #     - name: Checkout Code 
  #       uses: actions/checkout@v4

      # - name: Extract branch name
      #   run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      #   # id: extract_branch
  
      # - name: Tag commit
      #   uses: tvdias/github-tagger@v0.0.2
      #   with:
      #     repo-token: "${{ secrets.GH_TOKEN }}"
      #     tag: "0.02"
      
      # - name: Set Dist Version
      #   run: |
      #     # build_number="${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
      #     # echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV
      #     time_stamp="$(date +'%Y.%m.%d')"
      #     echo "NOW=$time_stamp" >> $GITHUB_ENV
      #     echo "${{ github.ref_name }}"
          
      # - name: Set outputs
      #   id: vars
      #   run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
      # - name: Set TIME
      #   run: |
      #     echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      #     echo "${{env.NOW}}"
    
      # - name: Create tag
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/${{ github.run_number }}-${{env.NOW}}-${{ env.sha_short }}',
      #         sha: context.sha
      #       })
      # - name: Run latest-tag
      #   uses: EndBug/latest-tag@latest
      #   with:
      #     tag-name: 0.0.7

      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      #   env:
      #     # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # if you don't want to set write permissions use a PAT token
      #     WITH_V: false
      
      # - name: Bump version and push tag
      #   uses: hennejg/github-tag-action@v4.1.jh1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
    
      # - uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      
      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}

              
      # - name: Autotag      
      #   uses: phish108/autotag-action@v1.1.64

      # - name: Auto tag         
      #   uses: Klemensas/action-autotag@1.2.3
      #   with:
      #     GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"

      # - name: Conventional Changelog Action
      #   uses: TriPSs/conventional-changelog-action@v5.2.1
      #   with:
      #     github-token: ${{ secrets.GH_TOKEN }}
      
      # - name: Create/Update tag    
      #   uses: rickstaa/action-create-tag@v1.7.2
      #   with:
      #     tag: "${{ github.run_number }}" 
      
      # - name: Updated related tags
      #   uses: haya14busa/action-update-semver@v1.2.1
      #   with:
      #     tag: "${{ github.run_number }}"
      
    
      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     dry_run: true
         
      # - name: Git Semantic Version 
      #   id: tag_version
      #   uses: PaulHatch/semantic-version@v5.4.0
      #   with:
      #     # tag_prefix: "v"
      #     major_pattern: "MAJOR"
      #     minor_pattern: "MINOR"
      
      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # if you don't want to set write permissions use a PAT token
      #     WITH_V: false

      # - name: Create Tag
      #   id: create_tag
      #   uses: jaywcjlove/create-tag-action@main
      
      # - name: Bump version and push tag
      #   uses: hennejg/github-tag-action@v4.3.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      
      # - name: Bump version and push tag
      #   if: github.event_name == 'workflow_dispatch'
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
       
      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: miguelfito/github-bump-and-tag-action@v1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}

      # - name: Create a GitHub release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.tag_version.outputs.new_tag }}
      #     release_name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ steps.tag_version.outputs.changelog }}
      
      # - uses: jveldboom/action-conventional-versioning@v1
      #   id: version

      # - name: Create GitHub Release
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: |
      #     gh release create "${{ steps.version.outputs.version-with-prefix }}" \
      #       --generate-notes \
      #       --target "${{ github.sha }}"

      # - name: Update Major Tag
      #   # env:
      #   #   MAJOR: ${{ steps.version.outputs.major }} 
      #   run: |
      #     git tag -d 0.0.1 || true
      #     git push origin :refs/tags/0.0.1
      #     git tag 0.0.1 
      #     git push origin 0.0.1

      # - name: Update major/minor semver  
      #   uses: haya14busa/action-update-semver@v1.2.1


      # - name: Create tag
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/${{ steps.tag_version.outputs.version }}',
      #         sha: context.sha
      #       })
      
      # - name: Create Release
      #   id: create_release
      #   uses: xaprier/actions-semver@latest
      #   with:
      #     draft: false
      #     prerelease: false
      #     include-letter-v: true
      #     token: ${{ secrets.GH_TOKEN }}
      

      # - name: Bump version and push tag
      #   uses: hennejg/github-tag-action@v4.3.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
    

  Tags:
    runs-on: ubuntu-latest
    # if: github.event_name == 'workflow_dispatch'
    # concurrency: ci-${{ github.ref }}
    permissions: write-all
    steps:  
      # - name: checkout repo
      #   uses: actions/checkout@v4
      # - name: Minor version for each merge
      #   id: taggerDryRun
      #   uses: anothrNick/github-tag-action@1.67.0
      #   env:
      #     # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     WITH_V: true
      #     DEFAULT_BUMP: patch
      #     # DRY_RUN: true
  
      # - name: echo new tag
      #   run: |
      #     echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"
      # - name: echo tag
      #   run: |
      #     echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
      # - name: echo part
      #   run: |
      #     echo "The version increment was: ${{ steps.taggerDryRun.outputs.part }}"

      # - name: Increment version
      #   id: increment-version
      #   uses: RichardInnocent/semantic-versioning-git@v0.0.2

      # # Everything below here shows how you might use the results of the action...

      # - name: Print if version changed
      #   # if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
      #   run: echo "The new version is now $new_version"
      #   env:
      #     new_version: ${{ steps.increment-version.outputs.new-version }}
          
      # - name: Create tag
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/${{ steps.increment-version.outputs.new-version }}',
      #         sha: context.sha
      #       })

      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v4.0.0
      #   id: semantic
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # - name: version
      #   id: version
      #   uses: flatherskevin/semver-action@1.0.13
      #   with:
      #     incrementLevel: patch
      #     source: tags
          
      # - name: Release
      #   uses: softprops/action-gh-release@v1.4.0
      #   with:
      #     name: ${{ steps.version.outputs.nextVersion }}
      #     tag_name: ${{ steps.version.outputs.nextVersion }}


      # - name: Bump version and push tag
      #   id: version
      #   uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      #   env:
      #     DEFAULT_BUMP: patch
      #     # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # if you don't want to set write permissions use a PAT token
      #     WITH_V: true 
      #     # DRY_RUN: true
          
      # - name: Create tag
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/${{ github.run_number }}-${{ steps.version.outputs.new_tag }}',
      #         sha: context.sha
      #       })
  
      # - name: Bump version and push tag
      #   uses: Magikon/github-tag-action@5.0.0
      #   id: tag
      #   env:
      #     DEFAULT_BUMP: patch
      #     SUFFIX: ${{ github.run_number }}
      #     MAJOR: "BREAKING*CHANGE|*#major*"
      #     MINOR: "*feat*|*#minor*"
      #     PATCH: "*fix*|*chore*|*docs*|*update*|#patch"
      #     FORCE: true
      #     OVERWRITE: true

      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     # DRY_RUN: true
      #     default_bump: patch
      #     github_token: ${{ secrets.GH_TOKEN }}
      
      # - name: Bump version and push tag
      #   uses: hennejg/github-tag-action@v4.3.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     dry_run: true
      #     tag_prefix: v
      
      # - uses: rymndhng/release-on-push-action@master
      #   with:
      #     bump_version_scheme: minor

      # - name: Generate build number
      #   # if: github.event_name == 'workflow_dispatch'
      #   uses: onyxmueller/build-tag-number@v1.0.3   
      #   with:
      #     token: ${{ secrets.GH_TOKEN }}
          
      # - name: Print new build number
      #   run: echo "Build number is ${env:BUILD_NUMBER}"

      # - name: Get next version
      #   uses: reecetech/version-increment@2023.10.2
      #   id: version
      #   with:
      #     scheme: semver
      #     increment: patch

      - name: Get next version
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          use_api: true
          
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.version.outputs.version }}',
              sha: context.sha
            })
