
name: github-script

on:
  workflow_dispatch:

env:
  USER_NAME: "mask"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      # - uses: actions/github-script@v7
      #   id: set-result
      #   with:
      #     script: return "Hello!"
      #     result-encoding: string
      # - name: Get result
      #   run: echo "${{steps.set-result.outputs.result}}"
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/0.0.1',
              sha: context.sha
            })
