name: CI

on:
  workflow_dispatch:

env:
  USER_NAME: "mask"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.json"]'
        env:
          userName: "${{ env.USER_NAME }}"
          password: "${{ secrets.PWord }}"

      # - name: Replace User Name and Password
      #   run: |
      #     Get-ChildItem -Filter *.json | ForEach-Object {
      #         $content = Get-Content $_.FullName | Out-String | ConvertFrom-Json
      #         $content.password = "${{ secrets.PWord }}"
      #         $content.userName = "${{ env.USER_NAME }}"
      #         $content | ConvertTo-Json | Set-Content $_.FullName
      #     }

      # - name: Replace User Name and Password
      #   run: |
      #     Get-ChildItem -Filter *.json | ForEach-Object {
      #         $content = Get-Content $_.FullName
      #         $content = $content -replace '#{PWord}#', "${{ secrets.PWord }}" -replace '#{UName}#', "${{ env.USER_NAME }}"
      #         $content | Set-Content $_.FullName
      #     }

      - name: Show JSON Contents
        run: Get-Content Example.json
